[theme]
primaryColor="#FF4B4B"
backgroundColor="#27262C"
secondaryBackgroundColor="#4044ED"
textColor="#FFFFFF"
font="sans serif"

[client]
toolbarMode = "auto"
showSidebarNavigation = false
showErrorDetails = false

