spring:
  config:
    import:
      'file:./secrets.yml'
  application:
    name: 'Utilitector Backend'
#  jpa:
#    database: postgresql
  data:
    mongodb:
      database: main
server:
  port: 8080
  servlet:
    context-path: '/api'