spring:
  config:
    import:
      'file:./secrets.yml'
  application:
    name: 'Utilitector Backend'
  jpa:
    database: postgresql
  data:
    mongodb:
      host: 'mongodb+srv://utilitector.4fknr.mongodb.net/?retryWrites=true&w=majority&appName=Utilitector'
server:
  port: 8080